name: "mkhouse-obsidian-livesync"

services:

  mkhouse-obsidian-livesync:
    image: "couchdb:latest"
    container_name: "mkhouse-obsidian-livesync"
    hostname: "mkhouse-obsidian-livesync"
    restart: "unless-stopped"
    user: "1000:1000"
    dns:
      - "1.1.1.1"
      - "4.4.4.4"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Sao_Paulo"
      COUCHDB_USER: "${COUCHDB_USER}"
      COUCHDB_PASSWORD: "${COUCHDB_PASSWORD}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "mkhouse-obsidian-livesync-data:/opt/couchdb/data"
      - "mkhouse-obsidian-livesync-etc:/opt/couchdb/etc"
    networks:
      mkhouse-vpc-net:

networks:
  mkhouse-vpc-net:
    external: true

volumes:
  mkhouse-obsidian-livesync-data:
    external: true
  mkhouse-obsidian-livesync-etc:
    external: true
